### ISSUE TITLE
selecting language from multilingual eit files

### ISSUE THREAD

**Issue by ghost** [betonme/e2openplugin-EnhancedMovieCenter#136]
Hello . about ifo in enhanced Movie center can it be fixed.
regars seth

**Comment by Seth72** [comment]
is this request enough

**Comment by betonme** [comment]
The request is to make the usage of the IFO files optional
Or 
To make an option to define the preferred files: EIT, META, IFO

**Comment by Seth72** [comment]
is it a ongoing Project or it works now

**Comment by Seth72** [comment]
would like to know when i can install this plugin on of my favorite
regard seth

**Comment by Seth72** [comment]
can anyboby at this git help me where i can add to this plugin will read correct epg data . in witch file do i fix this .

**Comment by betonme** [comment]
Do You have *.ifo files or *.eit

**Comment by Seth72** [comment]
Eit
Den 9 dec 2015 11:13 skrev "Frank Glaser" <notifications@github.com>:

**Comment by Seth72** [comment]
yourfilename.eit
yourfilename.ts.ap
yourfilename.ts.cuts
yourfilename.ts.mets
yourfilename.ts.sc
Den 9 dec 2015 11:13 skrev "Frank Glaser" <notifications@github.com>:

**Comment by Seth72** [comment]
correction
yourfilename.eit
yourfilename.ts.ap
yourfilename.ts.cuts
yourfilename.ts.meta
yourfilename.ts.sc

2015-12-09 11:29 GMT+01:00 Seth Larsson <seth.larsson72@gmail.com>:

**Comment by betonme** [comment]
Within the EMC Seup what is Your prefered EPG language?

**Comment by Seth72** [comment]
swedish

2015-12-09 12:24 GMT+01:00 Frank Glaser <notifications@github.com>:

**Comment by Seth72** [comment]
why cant this be fixed anyone ..please ...

**Comment by Seth72** [comment]
is there absolute no way to fix this . no one  can give any answer . its the best one but if this would be fixed it would be even better

**Comment by Fischreiher** [comment]
No offense meant, but, "congratulations", after a year of crying for help, for the first time you have now provided at least a semi accurate description of your problem. If you manage posting a really accurate one, you might actually get help.

**Comment by Seth72** [comment]
Crying am i , haha , seem to you too dont gets this error but i do , so if
you are a coder then get in to the problem or simple shut up, because
betonme gets what i mean . Go back to school....

Den 18 okt. 2016 10:47 em skrev "Fischreiher" <notifications@github.com>:

No offense meant, but, "congratulations", after a year of crying for help,
for the first time you have now provided at least a semi accurate
description of your problem. If you manage posting a really accurate one,
you might actually get help.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/betonme/e2openplugin-EnhancedMovieCenter/issues/136#issuecomment-254634550>,
or mute the thread

**Comment by Fischreiher** [comment]
Dear Seth, I sincerely apologize for my sarcasm yesterday, I really didn't mean to offend you. My advise to describe the problem better was well meant, maybe you could take it serious. Not all designers have the time for collecting pieces of information distributed to multiple issue threads you have opened here at github. Also you may consider posting in a forum.

**Comment by Seth72** [comment]
Im not a coder so dont know how to describe it better.  about ifo is
betonme that wrote that not me. The problem i have is in eit file from
recording a movie is in that file its the epg data about the movie,  actors
and more. In this flle i get about 3 to 4 different languish that show up
in emc and its dont sort or hide example i get swedish norwigean finnish
and only want to see swedish.this shows up when i start emc under minitv or
in emc press epg.

Sorry for my rude answer
Regards seth

Den 19 okt. 2016 9:06 fm skrev "Fischreiher" <notifications@github.com>:

**Comment by Fischreiher** [comment]
This is a very clear description, thank you.
What happens when you watch live TV on a channel broadcasting multi language EPG and you press the info button, and how about the standard Movie Player? Do you see all languages or only Swedish in these cases? I'm asking to see whether a mechanism for selecting a specific language exists elsewhere in enigma2 (outside EMC).

**Comment by Seth72** [comment]
Hello.  Yes standard media player shows only swedish. Same with live tv i
only see swedish. Its is in eit file i think emc have so sort it out. Ihave
post in vuplus support forum with eit file. I know that you coder not have
all the time for this. I respect that.i tried my self byr thats hard to do.

Den 19 okt. 2016 12:10 em skrev "Fischreiher" <notifications@github.com>:

This is a very clear description, thank you.
What happens when you watch live TV on a channel broadcasting multi
language EPG and you press the info button, and how about the standard
Movie Player? Do you see all languages or only Swedish in these cases? I'm
asking to see whether a mechanism for selecting a specific language exists
elsewhere in enigma2 (outside EMC).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/betonme/e2openplugin-EnhancedMovieCenter/issues/136#issuecomment-254770897>,
or mute the thread

**Comment by Fischreiher** [comment]
I see. Which image are you using?
And could you upload an example of a multi language eit file here?

**Comment by Seth72** [comment]
Right now blackhole.  The same problem is with vti too

Den 19 okt. 2016 12:25 em skrev "Fischreiher" <notifications@github.com>:

**Comment by Fischreiher** [comment]
Just checking the obvious: Did you notice that EMC has its own config setting for the preferred EPG language?

https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/5b46b7c1195c0f8777ec9bbd81bd1b099bbbeedd/src/EnhancedMovieCenter.py#L502

**Comment by Seth72** [comment]
yes and i have Swedish there  and thats dont work

**Comment by Seth72** [comment]
the same issue is with openatv just tryid it

**Comment by Fischreiher** [comment]
At a first glance, I cannot see any obvious blunder in the code, EMC and enigma2 (openATV version) are using the same method:
`UsageConfig.py:           eServiceEvent.setEPGLanguage(configElement.value)`
`EnhancedMovieCenter.py:         eServiceEvent.setEPGLanguage(config.EMC.epglang.value)`

**Comment by Seth72** [comment]
hello , i dont Think there is a blunder at all in emc , but im not a coder.
if i remeber from the beginning it was swiss-mad and coolman that did this ?.
it was named enigma2-plugin-extensions-suomipoeka_1.0.1_all. dont know whats different in coding but this is an old plugin and its does only show the right epg ,its reads multi eit.

**Comment by Seth72** [comment]
found it
[enigma2-plugin-extensions-suomipoeka_1.0.1_all.zip](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/543589/enigma2-plugin-extensions-suomipoeka_1.0.1_all.zip)

**Comment by Fischreiher** [comment]
To enable debugging, may I kindly ask you (again) to post an example of a multilingual eit file.

Also please report these items from your  /etc/enigma2/settings : 
`config.EMC.epglang.value
config.autolanguage.audio_epglanguage
config.autolanguage.audio_epglanguage_alternative`

Thanks.

**Comment by Seth72** [comment]
[20161015 2058 - C More First HD - Bridge of Spies.zip](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/543836/20161015.2058.-.C.More.First.HD.-.Bridge.of.Spies.zip)

all  Swedish

**Comment by betonme** [comment]
@Fischreiher Thanks that You are investigate the issue.

There is a huge difference between Suomipoeka and EMC.

Suomipoeka is using the Enigma2 Converter and EMC has its own Converters.
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/master/src/EitSupport.py

I think we need to filter the short_event_descriptor and extended_event_descriptor

**Comment by Seth72** [comment]
I thanking you for taking the time

**Comment by Fischreiher** [comment]
@betonme, thanks for your comment, it would be really nice if you could look into this. I'm not sure why EMC is using its own converter while the enigma2 converter seems to be working properly at least in this situation, but of course there may be good reasons I'm not aware of. Maybe the missing filter could be "legally stolen" from enigma2?

@Seth72, could you please post a multilingual eit file (i.e. one with more than one language, a file showing your problem). The reason is that in Germany I couldn't find any service broadcasting multilingual EPG, so we require a file from you for testing. Thank you.

**Comment by Seth72** [comment]
here comes some more and  hope you make the change to enigmas own converter

[movie eit files.zip](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/546182/movie.eit.files.zip)

regards Seth

**Comment by Seth72** [comment]
and Fischreiher  will thanking you again, for the  time and effort at this

**Comment by Seth72** [comment]
Ok.  Will use it anyway. Will look latet after eit editor.  Regards seth

Den 20 okt. 2016 7:48 em skrev "Fischreiher" <notifications@github.com>:

**Comment by Seth72** [comment]
Cant emc use enigma converters

Den 21 okt. 2016 12:06 em skrev "Frank Glaser" <notifications@github.com>:

**Comment by betonme** [comment]
Yes. 

You have to adapt Your Skin.

If You use the EMC default skin for e.g. the one with a width of 1280 pixels
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/blob/master/src/CoolSkin/EMCSelection_1280.xml

Change the lines 
<widget source="Service" render="Label" position="50,370" size="425,22" font="Regular; 19" zPosition="2" foregroundColor="#00bab329" backgroundColor="#444444" transparent="1" halign="center" >
		<convert type="EMCMovieInfo">ShortDescription</convert>
	</widget>
	<widget source="Service" render="Label" position="50,395" size="425,243" font="Regular;19" foregroundColor="#FFFFFF" backgroundColor="#444444" transparent="1" halign="left" valign="top">
		<convert type="EMCEventName">ExtendedDescription</convert>
	</widget>
	
to

<widget source="Service" render="Label" position="50,370" size="425,22" font="Regular; 19" zPosition="2" foregroundColor="#00bab329" backgroundColor="#444444" transparent="1" halign="center" >
		<convert type="MovieInfo">ShortDescription</convert>
	</widget>
	<widget source="Service" render="Label" position="50,395" size="425,243" font="Regular;19" foregroundColor="#FFFFFF" backgroundColor="#444444" transparent="1" halign="left" valign="top">
		<convert type="EventName">ExtendedDescription</convert>
	</widget>

**Comment by Seth72** [comment]
It didnt work .

 So strange i saw old messages uust appear here , why. Something i wrote before

**Comment by petrkl12** [comment]
As you are really **tireless :)** I have repair your issue and some others connected with eit. 
Could you check if it works?

unzip file, copy file into right folder (/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/) + restart GUI

[EitSupport.zip](https://github.com/betonme/e2openplugin-EnhancedMovieCenter/files/554451/EitSupport.zip)
