### ISSUE TITLE
Service Hisilicon Issue

### ISSUE THREAD

**Issue by ozone1864** [betonme/e2openplugin-EnhancedMovieCenter#261]
Dear betonme,
When using hisilicon service as original player we can't resume movies and can't see their progress bar on EMC (Enhanced Movie Center) which is problem related with ".cuts" file. Unless we remove the service hisilicon but this will make the playback bad. So please fix this.
Tried this on hundreds of videos files but still same problem on openATV
Thanks in advance
System : OpenATV 6.2/6.3

**Comment by dhwz** [comment]
What do you mean with "hisilicon service as original player"?
Focus of this plugin is primarily for dreamboxes, there will be no specific modifications for other hardware/software.
Nevertheless this is not something what has to be fixed in EMC, sounds like a HW specific issue, so your manufacturer is responsible.

**Comment by ozone1864** [comment]
@dhwz 
hisilicon service as original player yes is causing this issue after deleting it the issue is solved,
But deleting this player will cause lot of playback problems on hisilicon chipset devices.
What should I do ?

**Comment by dhwz** [comment]
I don't know, contact your manufacturer to fix the issues related to the standard player (the only one which is supported).
