### ISSUE TITLE
Enhanced Movie Center Setup ( issue )

### ISSUE THREAD

**Issue by nunigaia** [betonme/e2openplugin-EnhancedMovieCenter#267]
How to reproduce:

1) Go to Enhanced Movie Center Setup ( under plugins browser ).

2) Don´t make any settings modification.

3) Press GREEN ( for SAVE ), the none modifications you have done.

4) You are not promped to restart modifications.

5) Without restart enigma2, enter another time Enhanced Movie Center Setup.

6) The system hangs, and you have to kill enigma2 or power off your STB.

Image used ( Open BlackHole 4.3.009 )

best regards
nunigaia

**Comment by dhwz** [comment]
not a bug working properly with supported images

**Comment by Alexwilmac** [comment]
Which are the supported images? So, you are not interested in having a plugin working on a wider range of enigma2 images? This goes against the reputation of your plugin, in my view.
And, to complete what nunigaia wrote, the significance of the problem comes from the fact that, it happens not only if you enter and exit from EMC setup, but, above all, if you enter the setup, change something, then you save exit and, if you remember to change another setting and you enter again the setup, as you hadn't been prompted for a GUI restart before the previous step, you cause the image to hang.
The prompt about the need to restart is important, is not a secondary detail and you should be the most interested in this lack.
Or, as an alternative, it should be made impossible to enter again the setup before having restarted the GUI.

**Comment by dhwz** [comment]
Sorry but it's not my plugin.
But basically this plugin was always inteded for dreamboxes only, there is nobody who cares about or supports images other than Opendreambox OE2.5/2.6 currently.
Also the setup is working as intended if some other (unsupported) image is not working I don't care.
